### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by brandonsaldan** [AlanBaumgartner/instagram_checker#2]
Hi, I'm pretty noob at Python so please forgive me if this is an easy fix on my end.
When I import a .txt and login, I get:

`C:\Users\brensalsa\Desktop\instagram_checker-master>python instagram_checker.py
Traceback (most recent call last):
  File "instagram_checker.py", line 129, in run
    loop.run_until_complete(self.main())
  File "C:\Users\brensalsa\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 466, in run_until_complete
    return future.result()
  File "instagram_checker.py", line 155, in main
    cont = await self.login(self.igname, self.igpass, session)
  File "instagram_checker.py", line 168, in login
    csrftoken = csrftoken.split('csrf_token": "')[1].split('"')[0]
IndexError: list index out of range`

in cmd. Am I doing something wrong?

**Comment by ooaj** [comment]
See: https://github.com/alanbaumgartner/instagram_checker/pull/3
